--------------------------------------------------------------------------------
-- Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.
--------------------------------------------------------------------------------
--   ____  ____
--  /   /\/   /
-- /___/  \  /    Vendor: Xilinx
-- \   \   \/     Version: M.81d
--  \   \         Application: netgen
--  /   /         Filename: .vhd
-- /___/   /\     Timestamp: Sat Nov 26 00:57:49 2011
-- \   \  /  \ 
--  \___\/\___\
--             
-- Command	: -intstyle ise -ar Structure -tm Registe_File -w -dir netgen/synthesis -ofmt vhdl -sim Registe_File.ngc Registe_File_synthesis.vhd 
-- Device	: xc6slx100-3-fgg484
-- Input file	: Registe_File.ngc
-- Output file	: C:\JUAN CORRALES\UTP\SEMESTRE 1102\ARQUITECTURA DE COMPUTADORES\RegisterFile\netgen\synthesis\Registe_File_synthesis.vhd
-- # of Entities	: 1
-- Design Name	: Registe_File
-- Xilinx	: C:\Xilinx\12.4\ISE_DS\ISE\
--             
-- Purpose:    
--     This VHDL netlist is a verification model and uses simulation 
--     primitives which may not represent the true implementation of the 
--     device, however the netlist is functionally correct and should not 
--     be modified. This file cannot be synthesized and should only be used 
--     with supported simulation tools.
--             
-- Reference:  
--     Command Line Tools User Guide, Chapter 23
--     Synthesis and Simulation Design Guide, Chapter 6
--             
--------------------------------------------------------------------------------

